# Generated by Django 2.0.1 on 2018-01-22 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sr_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=30)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, to='sr_core.Service')),
            ],
        ),
    ]
